source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CameraView_Example', :exclusive => true do
  pod "CameraView", :path => "../"
end

target 'CameraView_Tests', :exclusive => true do
  pod "CameraView", :path => "../"

  
end
